### ISSUE TITLE
Start-Migrations fails if there is a space in the directory path

### ISSUE THREAD

**Issue by Mark-Robinson** [bradyholt/dbup-consolescripts#1]
I get the error below when running start-migrations. My folder path is "C:\TFS\FACE\Argon_Main Solution..." so it appears the space in the folder path is breaking the command.

The term 'C:\TFS\FACE\Argon_Main' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:24
- C:\TFS\FACE\Argon_Main <<<<  Solution_Latest Release\Source\Argon_Projects\Face.Argon.Database.Upgrade\bin\Debug\Face.Argon.Database.Upgrade.exe --fromconsole
  - CategoryInfo          : ObjectNotFound: (C:\TFS\FACE\Argon_Main:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by bradymholt** [comment]
Fixed by f0a19fe0cea26db13420c157df78ca9cbb94a49a, released as version 1.0.9.
