### ISSUE TITLE
Configurable date formats

### ISSUE THREAD

**Issue by scott-wi** [bradyholt/dbup-consolescripts#13]
Really awesome project. However, I'm on a project where we're mixing EFCore with DbUp and we'd like to use the same date format as EFCore's migrations, which use a 4-digit year. Any possibility the library could be updated to support a project config file where you could change the default date format?

**Comment by bradymholt** [comment]
Thanks for the feedback.  I'd welcome a PR for this type of feature to customize the [date format](https://github.com/bradymholt/dbup-consolescripts/blob/master/dbup-consolescripts.psm1#L74).  I'm going to close this but feel free to submit a PR.  Thanks!
