### ISSUE TITLE
Build do not work when active configuration is not "Debug"

### ISSUE THREAD

**Issue by andreminelli** [bradyholt/dbup-consolescripts#4]
On Package Manager Console this message is logged:

Value does not fall within the expected range.
At C:\Users\andre\Take\Smart\Itau-ColchaoDeAcordos\ItauDebitoAutomatico\packages\dbup-consolescripts.1.1.1\tools\dbup-consolescripts.psm1:50 char:3
+   $dte.Solution.SolutionBuild.BuildProject("Debug", $project.FullName ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException

**Comment by bradymholt** [comment]
Thanks @andreminelli - do you know of an easy fix for this?  I'd welcome a PR for it.

**Comment by andreminelli** [comment]
I am trying right now, but I have no experience with Package Manager Console integration. Can you point me any reference, specially for testing things?

**Comment by andreminelli** [comment]
I think I got it.

**Comment by kkrol** [comment]
@bradymholt  It seems that this issue is resolved
