### ISSUE TITLE
New-Migration ignores wildcard script reference in project file

### ISSUE THREAD

**Issue by eugenej** [bradyholt/dbup-consolescripts#8]
When I run new-migration it still adds scripts reference into project file even when file has wildcard reference for script files (see example below). It will be great to avoid this.

```
<ItemGroup>
    <EmbeddedResource Include="scripts\*.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="scripts\170922172237_test.sql" />
  </ItemGroup>
```

**Comment by beylkhanovdamir** [comment]
@bradyholt 
there are any plans to upgrade dbup projects to .net standard?

**Comment by kkrol** [comment]
I have created a PR for that issue.
Adding new method to PS module  called - New-Migration-Dynamic
